// Another Quality Modpack 2

onEvent('recipes', event => {
    event.custom({
        "type": "artis:end_game_crafting_shapeless",
        "ingredients": [{
            "item": "agape_space:aluminum_ingot"
        }, {
            "item": "archon:glisteel_ingot"
        }, {
            "item": "betterend:aeternium_ingot"
        }, {
            "item": "betterend:terminite_ingot"
        }, {
            "item": "betterend:thallasium_ingot"
        }, {
            "item": "betternether:cincinnasite_ingot"
        }, {
            "item": "botania:elementium_ingot"
        }, {
            "item": "botania:gaia_ingot"
        }, {
            "item": "botania:manasteel_ingot"
        }, {
            "item": "botania:terrasteel_ingot"
        }, {
            "item": "byg:pendorite_ingot"
        }, {
            "item": "dml-refabricated:glitch_ingot"
        }, {
            "item": "gobber2:gobber2_ingot"
        }, {
            "item": "gobber2:gobber2_ingot_end"
        }, {
            "item": "gobber2:gobber2_ingot_nether"
        }, {
            "item": "graveyard:dark_iron_ingot"
        }, {
            "item": "indrev:enriched_nikolite_ingot"
        }, {
            "item": "indrev:nikolite_ingot"
        }, {
            "item": "lightestlamp:lanthanum_ingot"
        }, {
            "item": "minecraft:gold_ingot"
        }, {
            "item": "minecraft:iron_ingot"
        }, {
            "item": "minecraft:netherite_ingot"
        }, {
            "item": "mobz:amat_ingot"
        }, {
            "item": "mobz:boss_ingot"
        }, {
            "item": "mobz:hardenedmetal_ingot"
        }, {
            "item": "modern_industrialization:antimony_ingot"
        }, {
            "item": "modern_industrialization:beryllium_ingot"
        }, {
            "item": "modern_industrialization:cadmium_ingot"
        }, {
            "item": "modern_industrialization:cupronickel_ingot"
        }, {
            "item": "modern_industrialization:he_mox_ingot"
        }, {
            "item": "modern_industrialization:he_uranium_ingot"
        }, {
            "item": "modern_industrialization:kanthal_ingot"
        }, {
            "item": "modern_industrialization:le_mox_ingot"
        }, {
            "item": "modern_industrialization:le_uranium_ingot"
        }, {
            "item": "modern_industrialization:manganese_ingot"
        }, {
            "item": "modern_industrialization:nickel_ingot"
        }, {
            "item": "modern_industrialization:plutonium_ingot"
        }, {
            "item": "modern_industrialization:silicon_ingot"
        }, {
            "item": "modern_industrialization:stainless_steel_ingot"
        }, {
            "item": "modern_industrialization:superconductor_ingot"
        }, {
            "item": "modern_industrialization:uranium_ingot"
        }, {
            "item": "mythicmetals:adamantite_ingot"
        }, {
            "item": "mythicmetals:aquarium_ingot"
        }, {
            "item": "mythicmetals:banglum_ingot"
        }, {
            "item": "mythicmetals:carmot_ingot"
        }, {
            "item": "mythicmetals:celestium_ingot"
        }, {
            "item": "mythicmetals:durasteel_ingot"
        }, {
            "item": "mythicmetals:hallowed_ingot"
        }, {
            "item": "mythicmetals:kyber_ingot"
        }, {
            "item": "mythicmetals:metallurgium_ingot"
        }, {
            "item": "mythicmetals:midas_gold_ingot"
        }, {
            "item": "mythicmetals:mythril_ingot"
        }, {
            "item": "mythicmetals:orichalcum_ingot"
        }, {
            "item": "mythicmetals:osmium_ingot"
        }, {
            "item": "mythicmetals:palladium_ingot"
        }, {
            "item": "mythicmetals:prometheum_ingot"
        }, {
            "item": "mythicmetals:quadrillum_ingot"
        }, {
            "item": "mythicmetals:runite_ingot"
        }, {
            "item": "mythicmetals:stormyx_ingot"
        }, {
            "item": "techreborn:advanced_alloy_ingot"
        }, {
            "item": "techreborn:aluminum_ingot"
        }, {
            "item": "techreborn:brass_ingot"
        }, {
            "item": "techreborn:bronze_ingot"
        }, {
            "item": "techreborn:chrome_ingot"
        }, {
            "item": "techreborn:electrum_ingot"
        }, {
            "item": "techreborn:invar_ingot"
        }, {
            "item": "techreborn:iridium_alloy_ingot"
        }, {
            "item": "techreborn:iridium_ingot"
        }, {
            "item": "techreborn:lead_ingot"
        }, {
            "item": "techreborn:mixed_metal_ingot"
        }, {
            "item": "techreborn:nickel_ingot"
        }, {
            "item": "techreborn:platinum_ingot"
        }, {
            "item": "techreborn:refined_iron_ingot"
        }, {
            "item": "techreborn:silver_ingot"
        }, {
            "item": "techreborn:steel_ingot"
        }, {
            "item": "techreborn:tin_ingot"
        }, {
            "item": "techreborn:titanium_ingot"
        }, {
            "item": "techreborn:tungsten_ingot"
        }, {
            "item": "techreborn:tungstensteel_ingot"
        }, {
            "item": "techreborn:zinc_ingot"
        }, {
            "item": "xps:soul_copper_ingot"
        }],
        "result": {
            "item": "kubejs:ultimate_ingot"
        }
    });
})