#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Sep 04 10:53:18 PDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL.zip
enableShaders=true
