#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Nov 27 09:49:19 PST 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL.zip
enableShaders=true
