#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jun 04 11:34:28 PDT 2024
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=BSL.zip
enableShaders=true
