
[general]
	#Show a black background box behind plaques. Disabled by default as it doesn't work with shaders.
	plaque_background = false
	#Distance to the mob at which plaques will still be visible. The distance is halved when the mob is crouching.
	#Range: > 0
	max_render_distance = 64
	#Selectors for choosing mobs to render plaques for.
	#Allowed Values: ALL, TAMED, TAMED_ONLY_OWNER, PLAYER, MONSTER, BOSS, MOUNT
	allowed_mob_selectors = ["ALL"]
	#Height offset from default position.
	#Range: > -2147483648
	height_offset = 0
	#Entities blacklisted from showing any plaques.
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. Path may use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*shulker_box" to match all shulker boxes no matter of color.
	mob_blacklist = ["minecraft:armor_stand", "automobility:automobile", "immersive_aircraft:*", "doom:iconofsin", "doom:motherdemon", "doom:gladiator", "doom:arch_maykr", "soulsweapons:freyr_sword_entity", "soulsweapons:comet_spear_entity", "soulsweapons:leviathan_axe_entity", "soulsweapons:big_moonlight_projectile", "soulsweapons:charged_arrow_entity"]
	#Show plaques from mobs obstructed by walls the player cannot see through.
	behind_walls = false
	#Are mob plaques enabled, toggleable in-game using the 'J' key by default.
	allow_rendering = true
	#Selectors for choosing mobs to prevent rendering plaques for, takes priority over allowed list.
	#Allowed Values: ALL, TAMED, TAMED_ONLY_OWNER, PLAYER, MONSTER, BOSS, MOUNT
	disallowed_mob_selectors = ["BOSS"]
	#Amount of pixels a row of plaques may take up, when exceeding this value a new row will be started.
	#Range: > 0
	max_plaque_row_width = 108
	#Show plaques for the entity picked by the crosshair only.
	picked_entity = false
	#Dynamically increase plaque size the further away the camera is to simplify readability.
	scale_with_distance = true
	#Render mob plaques below the mob's name tag instead of above.
	render_below_name_tag = false
	#Custom scale for rendering plaques.
	#Range: 0.05 ~ 2.0
	plaque_scale = 0.5

[health]
	#Hide health plaque when mob has full health.
	hide_when_full = false
	#Transition text colors depending on current percentage.
	shift_colors = true
	#Allow for rendering this type of plaque.
	allow_rendering = true
	#Show current amount as percentage instead of as absolute value.
	relative_value = false

[air]
	#Transition text colors depending on current percentage.
	shift_colors = true
	#Allow for rendering this type of plaque.
	allow_rendering = true
	#Show current amount as percentage instead of as absolute value.
	relative_value = false

[armor]
	#Allow for rendering this type of plaque.
	allow_rendering = true

[toughness]
	#Allow for rendering this type of plaque.
	allow_rendering = true

