blacklistedOres = ["lead", "tin", "silver", "salt", "bauxite", "iridium", "tungsten"]
enableNoEmiMessage = true
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = true
disableItemTagTooltips = true
newVersionMessage = false
enableHatchPlacementOverlay = true
colorWaterLava = true
enableDebugCommands = false
enableBidirectionalEnergyCompat = false
enableAe2Integration = true
generateOres = true
datagenOnStartup = false
loadRuntimeGeneratedResources = true
